-- MySQL Script generated by MySQL Workbench
-- 05/29/19 08:42:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ventas_repuestos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ventas_repuestos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ventas_repuestos` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ventas_repuestos` ;

-- -----------------------------------------------------
-- Table `ventas_repuestos`.`calidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`calidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`proveedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nit` VARCHAR(45) NULL,
  `nombre` VARCHAR(150) NULL,
  `direccion` VARCHAR(100) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nit_UNIQUE` (`nit` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`presentaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`presentaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`años`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`años` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `año` YEAR NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `año_UNIQUE` (`año` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`modelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`modelos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`fabricantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`fabricantes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`marcas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`subcategorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `categoria_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  INDEX `fk_subcategoria_categoria_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_subcategoria_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `ventas_repuestos`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo_barras` VARCHAR(50) NULL,
  `nombre` VARCHAR(200) NULL,
  `descripcion` VARCHAR(200) NULL,
  `año_id` INT NULL,
  `fabricante_id` INT NULL,
  `modelo_id` INT NULL,
  `calidad_id` INT NULL,
  `categoria_id` INT NULL,
  `subcategoria_id` INT NULL,
  `pasillo` VARCHAR(100) NULL,
  `marca_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_producto_año_idx` (`año_id` ASC),
  INDEX `fk_producto_fabricante_idx` (`fabricante_id` ASC),
  INDEX `fk_producto_modelo_idx` (`modelo_id` ASC),
  INDEX `fk_producto_calidad_idx` (`calidad_id` ASC),
  INDEX `fk_producto_categoria_idx` (`categoria_id` ASC),
  INDEX `fk_producto_subcategoria_idx` (`subcategoria_id` ASC),
  INDEX `fk_producto_marca_idx` (`marca_id` ASC),
  CONSTRAINT `fk_producto_año`
    FOREIGN KEY (`año_id`)
    REFERENCES `ventas_repuestos`.`años` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_fabricante`
    FOREIGN KEY (`fabricante_id`)
    REFERENCES `ventas_repuestos`.`fabricantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_modelo`
    FOREIGN KEY (`modelo_id`)
    REFERENCES `ventas_repuestos`.`modelos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_calidad`
    FOREIGN KEY (`calidad_id`)
    REFERENCES `ventas_repuestos`.`calidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `ventas_repuestos`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_subcategoria`
    FOREIGN KEY (`subcategoria_id`)
    REFERENCES `ventas_repuestos`.`subcategorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_marca`
    FOREIGN KEY (`marca_id`)
    REFERENCES `ventas_repuestos`.`marcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`sucursales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `ubicacion` VARCHAR(150) NULL,
  `telefono` VARCHAR(20) NULL,
  `email` VARCHAR(150) NULL,
  `clave_especial` VARCHAR(100) NULL,
  `correo_remitente` VARCHAR(150) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`bodegas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`bodegas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`bodega_sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`bodega_sucursal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bodega_id` INT NULL,
  `sucursal_id` INT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bodega_idx` (`bodega_id` ASC),
  INDEX `fk_sucursal_idx` (`sucursal_id` ASC),
  CONSTRAINT `fk_bodega`
    FOREIGN KEY (`bodega_id`)
    REFERENCES `ventas_repuestos`.`bodegas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sucursal`
    FOREIGN KEY (`sucursal_id`)
    REFERENCES `ventas_repuestos`.`sucursales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`bodega_sucursal_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`bodega_sucursal_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `producto_id` INT NULL,
  `bodega_id` INT NULL,
  `sucursal_id` INT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_producto_idx` (`producto_id` ASC),
  INDEX `fk_bodega_idx` (`bodega_id` ASC),
  INDEX `fk_sucursal_idx` (`sucursal_id` ASC),
  CONSTRAINT `fk_producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `ventas_repuestos`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bodega`
    FOREIGN KEY (`bodega_id`)
    REFERENCES `ventas_repuestos`.`bodegas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sucursal`
    FOREIGN KEY (`sucursal_id`)
    REFERENCES `ventas_repuestos`.`sucursales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`traslados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`traslados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sucursal_envia` INT NULL,
  `bodega_envia` INT NULL,
  `sucursal_recibe` INT NULL,
  `bodega_recibe` INT NULL,
  `producto_id` INT NULL,
  `fecha` DATE NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sucursal_envia_idx` (`sucursal_envia` ASC),
  INDEX `fk_bodega_envia_idx` (`bodega_envia` ASC),
  INDEX `fk_sucursal_recibe_idx` (`sucursal_recibe` ASC),
  INDEX `fk_bodega_recibe_idx` (`bodega_recibe` ASC),
  INDEX `fk_producto_idx` (`producto_id` ASC),
  CONSTRAINT `fk_sucursal_envia`
    FOREIGN KEY (`sucursal_envia`)
    REFERENCES `ventas_repuestos`.`sucursales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bodega_envia`
    FOREIGN KEY (`bodega_envia`)
    REFERENCES `ventas_repuestos`.`bodegas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sucursal_recibe`
    FOREIGN KEY (`sucursal_recibe`)
    REFERENCES `ventas_repuestos`.`sucursales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bodega_recibe`
    FOREIGN KEY (`bodega_recibe`)
    REFERENCES `ventas_repuestos`.`bodegas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `ventas_repuestos`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`correos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`correos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(150) NULL,
  `sucursal_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sucursal_idx` (`sucursal_id` ASC),
  CONSTRAINT `fk_sucursal`
    FOREIGN KEY (`sucursal_id`)
    REFERENCES `ventas_repuestos`.`sucursales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(200) NULL,
  `apellidos` VARCHAR(200) NULL,
  `email` VARCHAR(150) NULL,
  `telefono` VARCHAR(20) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(100) NULL,
  `rol_id` INT NULL,
  `sucursal_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_rol_idx` (`rol_id` ASC),
  INDEX `fk_sucursal_idx` (`sucursal_id` ASC),
  CONSTRAINT `fk_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `ventas_repuestos`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sucursal`
    FOREIGN KEY (`sucursal_id`)
    REFERENCES `ventas_repuestos`.`sucursales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`menus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(200) NULL,
  `nombre` VARCHAR(200) NULL,
  `icono` VARCHAR(150) NULL,
  `parent` INT NULL,
  `orden` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`permisos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `menu_id` INT NULL,
  `rol_id` INT NULL,
  `read` INT NULL,
  `insert` INT NULL,
  `update` INT NULL,
  `delete` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_menu_idx` (`menu_id` ASC),
  INDEX `fk_rol_idx` (`rol_id` ASC),
  CONSTRAINT `fk_menu`
    FOREIGN KEY (`menu_id`)
    REFERENCES `ventas_repuestos`.`menus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `ventas_repuestos`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`caja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL,
  `fecha_apertura` DATETIME NULL,
  `fecha_cierre` DATETIME NULL,
  `monto_apertura` DECIMAL(10,2) NULL,
  `monto_efectivo` DECIMAL(10,2) NULL,
  `estado` TINYINT(1) NULL,
  `observaciones` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ventas_repuestos`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`comprobantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`comprobantes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(200) NULL,
  `apellidos` VARCHAR(200) NULL,
  `cedula` VARCHAR(20) NULL,
  `telefono` VARCHAR(20) NULL,
  `direccion` VARCHAR(200) NULL,
  `nit` VARCHAR(45) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`tarjetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`tarjetas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(50) NULL,
  `comprobante_id` INT NULL,
  `estado` INT NULL,
  `fecha` DATETIME NULL,
  `tipo_pago` INT NULL,
  `cliente_id` INT NULL,
  `subtotal` DECIMAL(10,2) NULL,
  `iva` DECIMAL(10,2) NULL,
  `descuento` DECIMAL(10,2) NULL,
  `total` DECIMAL(10,2) NULL,
  `monto_efectivo` DECIMAL(10,2) NULL,
  `monto_credito` DECIMAL(10,2) NULL,
  `monto_tarjeta` DECIMAL(10,2) NULL,
  `tarjeta_id` INT NULL,
  `caja_id` INT NULL,
  `tipo_venta` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comprobante_idx` (`comprobante_id` ASC),
  INDEX `fk_cliente_idx` (`cliente_id` ASC),
  INDEX `fk_caja_idx` (`caja_id` ASC),
  INDEX `fk_tarjeta_idx` (`tarjeta_id` ASC),
  CONSTRAINT `fk_comprobante`
    FOREIGN KEY (`comprobante_id`)
    REFERENCES `ventas_repuestos`.`comprobantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `ventas_repuestos`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caja`
    FOREIGN KEY (`caja_id`)
    REFERENCES `ventas_repuestos`.`caja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarjeta`
    FOREIGN KEY (`tarjeta_id`)
    REFERENCES `ventas_repuestos`.`tarjetas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`comprobante_sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`comprobante_sucursal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comprobante_id` INT NULL,
  `sucursal_id` INT NULL,
  `serie` VARCHAR(20) NULL,
  `numero_inicial` INT NULL,
  `limite` INT NULL,
  `fecha_aprobacion_sat` DATE NULL,
  `fecha_vencimiento_sat` DATE NULL,
  `permitir_anulacion` TINYINT(1) NULL,
  `solicitar_nit` TINYINT(1) NULL,
  `dias_vencimiento` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `serie_UNIQUE` (`serie` ASC),
  INDEX `fk_sucursal_idx` (`sucursal_id` ASC),
  INDEX `fk_comprobante_idx` (`comprobante_id` ASC),
  CONSTRAINT `fk_sucursal`
    FOREIGN KEY (`sucursal_id`)
    REFERENCES `ventas_repuestos`.`sucursales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comprobante`
    FOREIGN KEY (`comprobante_id`)
    REFERENCES `ventas_repuestos`.`comprobantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`detalle_venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `venta_id` INT NULL,
  `producto_id` INT NULL,
  `cantidad` INT NULL,
  `precio` DECIMAL(10,2) NULL,
  `importe` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_venta_idx` (`venta_id` ASC),
  INDEX `fk_producto_idx` (`producto_id` ASC),
  CONSTRAINT `fk_venta`
    FOREIGN KEY (`venta_id`)
    REFERENCES `ventas_repuestos`.`ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `ventas_repuestos`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`compras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `serie` VARCHAR(45) NULL,
  `numero_comprobante` VARCHAR(45) NULL,
  `comprobante` INT NULL,
  `estado` TINYINT(1) NULL,
  `subtotal` DECIMAL(10,2) NULL,
  `total` DECIMAL(10,2) NULL,
  `tipo_pago` TINYINT(1) NULL,
  `proveedor_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_proveedor_idx` (`proveedor_id` ASC),
  CONSTRAINT `fk_proveedor`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `ventas_repuestos`.`proveedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`detalle_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`detalle_compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `compra_id` INT NULL,
  `producto_id` INT NULL,
  `precio` DECIMAL(10,2) NULL,
  `cantidad` INT NULL,
  `importe` DECIMAL(10,2) NULL,
  `presentacion_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_compra_idx` (`compra_id` ASC),
  INDEX `fk_producto_idx` (`producto_id` ASC),
  INDEX `fk_presentacion_idx` (`presentacion_id` ASC),
  CONSTRAINT `fk_compra`
    FOREIGN KEY (`compra_id`)
    REFERENCES `ventas_repuestos`.`compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `ventas_repuestos`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_presentacion`
    FOREIGN KEY (`presentacion_id`)
    REFERENCES `ventas_repuestos`.`presentaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`producto_presentaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`producto_presentaccion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `producto_id` INT NULL,
  `presentacion_id` INT NULL,
  `cantidad_unidades` INT NULL,
  `precio_venta` DECIMAL(10,2) NULL,
  `precio_compra` DECIMAL(10,2) NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_presentacion_idx` (`presentacion_id` ASC),
  INDEX `fk_producto_idx` (`producto_id` ASC),
  CONSTRAINT `fk_presentacion`
    FOREIGN KEY (`presentacion_id`)
    REFERENCES `ventas_repuestos`.`presentaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `ventas_repuestos`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`cuentas_cobrar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`cuentas_cobrar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `venta_id` INT NULL,
  `monto` DECIMAL(10,2) NULL,
  `estado` TINYINT(1) NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_venta_idx` (`venta_id` ASC),
  CONSTRAINT `fk_venta`
    FOREIGN KEY (`venta_id`)
    REFERENCES `ventas_repuestos`.`ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`pagos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cuenta_cobrar_id` INT NULL,
  `monto` DECIMAL(10,2) NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fl_cuenta_cobrar_idx` (`cuenta_cobrar_id` ASC),
  CONSTRAINT `fl_cuenta_cobrar`
    FOREIGN KEY (`cuenta_cobrar_id`)
    REFERENCES `ventas_repuestos`.`cuentas_cobrar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`cuentas_pagar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`cuentas_pagar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `compra_id` INT NULL,
  `monto` DECIMAL(10,2) NULL,
  `fecha` DATETIME NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_compra_idx` (`compra_id` ASC),
  CONSTRAINT `fk_compra`
    FOREIGN KEY (`compra_id`)
    REFERENCES `ventas_repuestos`.`compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_repuestos`.`cobros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_repuestos`.`cobros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cuenta_pagar_id` INT NULL,
  `monto` DECIMAL(10,2) NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cuenta_pagar_idx` (`cuenta_pagar_id` ASC),
  CONSTRAINT `fk_cuenta_pagar`
    FOREIGN KEY (`cuenta_pagar_id`)
    REFERENCES `ventas_repuestos`.`cuentas_pagar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
